/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: f61cce761c0cad8e320c285019f1c65b)
interface __BaseEnv_CloudflareEnv {
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	DB_PASSWORD: string;
	DATABASE_URL: string;
	DIRECT_URL: string;
	REDIS_URL: string;
	BACKEND_URL: string;
	NEXTAUTH_SECRET: string;
	NEXTAUTH_URL: string;
	AUTH_SECRET: string;
	AUTH_TRUST_HOST: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	STRIPE_SECRET_KEY: string;
	NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	STRIPE_PRICE_CREATOR: string;
	STRIPE_PRICE_PRO: string;
	STRIPE_PRICE_AGENCY: string;
	STRIPE_PRICE_CREDITS_100: string;
	STRIPE_PRICE_CREDITS_500: string;
	STRIPE_PRICE_CREDITS_1000: string;
	GEMINI_API_KEY: string;
	GEMINI_MODEL_NAME: string;
	WHISPER_MODEL_SIZE: string;
	WHISPER_DEVICE: string;
	WHISPER_COMPUTE_TYPE: string;
	UPLOAD_POST_API_KEY: string;
	STORAGE_TYPE: string;
	LOCAL_MEDIA_ROOT: string;
	MEDIA_PROXY_HOST: string;
	APP_NAME: string;
	APP_URL: string;
	APP_ENV: string;
	MAX_UPLOAD_SIZE_MB: string;
	MAX_VIDEO_DURATION_MINUTES: string;
	DEFAULT_FREE_CREDITS: string;
	MAX_CLIPS: string;
	MIN_CLIP_DURATION: string;
	MAX_CLIP_DURATION: string;
	YOUTUBE_COOKIES_PATH: string;
	SMART_CROP_ENABLED: string;
	SUBTITLES_ENABLED: string;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DB_PASSWORD" | "DATABASE_URL" | "DIRECT_URL" | "REDIS_URL" | "BACKEND_URL" | "NEXTAUTH_SECRET" | "NEXTAUTH_URL" | "AUTH_SECRET" | "AUTH_TRUST_HOST" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "STRIPE_SECRET_KEY" | "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" | "STRIPE_WEBHOOK_SECRET" | "STRIPE_PRICE_CREATOR" | "STRIPE_PRICE_PRO" | "STRIPE_PRICE_AGENCY" | "STRIPE_PRICE_CREDITS_100" | "STRIPE_PRICE_CREDITS_500" | "STRIPE_PRICE_CREDITS_1000" | "GEMINI_API_KEY" | "GEMINI_MODEL_NAME" | "WHISPER_MODEL_SIZE" | "WHISPER_DEVICE" | "WHISPER_COMPUTE_TYPE" | "UPLOAD_POST_API_KEY" | "STORAGE_TYPE" | "LOCAL_MEDIA_ROOT" | "MEDIA_PROXY_HOST" | "APP_NAME" | "APP_URL" | "APP_ENV" | "MAX_UPLOAD_SIZE_MB" | "MAX_VIDEO_DURATION_MINUTES" | "DEFAULT_FREE_CREDITS" | "MAX_CLIPS" | "MIN_CLIP_DURATION" | "MAX_CLIP_DURATION" | "YOUTUBE_COOKIES_PATH" | "SMART_CROP_ENABLED" | "SUBTITLES_ENABLED">> {}
}
